---
- name: Set following in kernel
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.conf
    reload: yes
  with_dict:
  - net.ipv4.ip_forward: 1
  - net.ipv4.conf.all.accept_redirects: 0
  - net.ipv4.conf.all.send_redirects: 0

- name: Configure ipsec.secrets and ipsec.conf
  template:
    src: "{{ item }}.j2"
    dest: "{{ strongswan_etc_dir }}/{{ item }}"
  notify: Restart Strongswan
  with_items:
  - ipsec.secrets
  - ipsec.conf

- name: Iptables Masquerade
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
    source: "{{ strongswan_rightsubnet }}"
    destination: "{{ strongswan_leftsubnet }}"
  become: yes