---
- name: Include variables OS
  include_vars: vars/{{ ansible_os_family }}.yml

- name: Change selinux
  include: "selinux.yml"
  when: ansible_os_family == "RedHat"
  tags: strongswan:selinux

- name: Update machine
  include: "update.yml"
  when: ansible_os_family == "RedHat"
  tags: strongswan:update

- name: Install strongswan
  include: "install.yml"
  when: ansible_os_family == "RedHat"
  tags: strongswan:install

- name: Configure Strongswan
  include: "configure.yml"
  when: ansible_os_family == "RedHat"
  tags: strongswan:configure

- name: Crontab
  include: "cron.yml"
  when: ansible_os_family == "RedHat"
  tags: strongswan:cron