---
- name: Update Repo
  raw: 'yum -y update --nogpgcheck'
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"

- name: Install python
  raw: yum install -y python python-pip
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"

- name: Install libpython
  raw: yum install -y libselinux-python
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"
 
- name: System Update
  package:
    name: "*"
    state: latest

- name: Install Epel Repo {{ ansible_os_family }}
  package:
    name:
      - epel-release
      - yum-utils
    state: present
  when: ansible_distribution != "Amazon"

- name: Install Epel Repo {{ ansible_os_family }} Amazon
  yum_repository:
    baseurl: https://dl.fedoraproject.org/pub/epel/7Server/x86_64/
    description: "Epel release."
    state: present
    name: epel-release
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"

- name: Install Yum-utils {{ ansible_os_family }}
  package:
    name: yum-utils
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"

- name: Install repo Zabbix 5.0 CentOS 8
  yum: 
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present
  when:          
    - ansible_os_family == "CentOS"
    - ansible_distribution != "Amazon"

- name: Install repo Zabbix 5.0 RedHat 7 Amazon
  shell: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
  when:          
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"

- name: Clearing yum cache
  command: yum clean expire-cache
  args:
    warn: false