---
- name: System Update
  package:
    name: "*"
    state: latest

- name: Install Epel Repo
  package:
    name:
      - epel-release
      - yum-utils
    state: present

- name: Install repo Zabbix 5.0
  yum: 
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present

- name: Clearing yum cache
  command: yum clean expire-cache
  args:
    warn: false