---
- name: System Update
  package:
    name: "*"
    state: latest

- name: Install Epel Repo {{ ansible_os_family }}
  package:
    name:
      - epel-release
      - yum-utils
    state: present
    when: ansible_os_family == "CentOS"

- name: Install Epel Repo {{ ansible_os_family }}
  yum_repository:
    baseurl: https://dl.fedoraproject.org/pub/epel/7Server/x86_64/
    description: "Epel release."
    state: present
    when: 
      - ansible_os_family == "RedHat"
      - ansible_distribution == "Amazon"

- name: Install Yum-utils {{ ansible_os_family }}
  package:
    name: yum-utils
    state: present
    when: 
      - ansible_os_family == "RedHat"
      - ansible_distribution == "Amazon"

- name: Install repo Zabbix 5.0
  yum: 
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present

- name: Clearing yum cache
  command: yum clean expire-cache
  args:
    warn: false