---
- name: System Update
  package:
    name: "*"
    state: latest

- name: Install Epel Repo
  package:
    name:
      - epel-release
      - yum-utils
    state: present

- name: Install repo Zabbix 5.0
  shell: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
  args:
    warn: false
  become: True

- name: Clearing yum cache
  command: dnf clean all
  args:
    warn: false
  become_user: root
  become: yes
  become_flags: '-i'