---
- name: Restart Zabbix_nginx
  service:
    name: "{{ zabbix_nginx }}"
    state: restarted

- name: Restart Zabbix_php
  service:
    name: "{{ zabbix_php }}"
    state: restarted

- name: Restart Zabbix_server
  service:
    name: "{{ zabbix_server }}"
    state: restarted

- name: Restart Zabbix_agent
  service:
    name: "{{ zabbix_agent }}"
    state: restarted